spring:
  freemarker:
    template-loader-path: "classpath:/templates"
    suffix: ".ftl"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:7777/gmail}
    password: ${DB_PASSWORD:root}
    username: ${DB_USERNAME:postgres}